move more of d_save / d_com_inf_game
zeldaret/tp pull request #141
Opened 2021-08-18 05:14 UTC by TakaRikka

cleaned up a bunch of stuff + some new matches too

2021-08-20 19:01 UTC, lepelog requested changes
Looks good, just a few things I noticed. Also, some functions still use the mangled names (like https://github.com/zeldaret/tp/blob/1a75f14acb14be13cd5a8c727a00964acee89227/src/d/d_item.cpp#L1191 ), I think it would be good to change them to the demangled names if possible

2021-08-21 21:29 UTC, lepelog approved these changes

2021-08-22 18:53 UTC, lepelog commented on src/d/com/d_com_inf_game.cpp
> +    } else if ((u8)(selectItem - NORMAL_BOMB) <= 2 || selectItem == BOMB_ARROW) {
`(u8)(selectItem - NORMAL_BOMB) <= 2` is a compiler optimization for checking if selectItem is equal to `NORMAL_BOMB` or the 2 values after it in the enum. It should match with 3 separate comparisons as well and that's more readable imo

2021-08-22 19:18 UTC, ProjectRevoTPP commented on src/d/com/d_com_inf_game.cpp
> +    } else if ((u8)(selectItem - NORMAL_BOMB) <= 2 || selectItem == BOMB_ARROW) {
I think I already posted about this in the discord a while back as it's needed for isBomb.

2021-08-22 19:22 UTC, TakaRikka commented on src/d/com/d_com_inf_game.cpp
> +    } else if ((u8)(selectItem - NORMAL_BOMB) <= 2 || selectItem == BOMB_ARROW) {
yea i prob missed it before. good to know now

2021-08-23 20:47 UTC, merged