Port JStudio work to new branch
zeldaret/tp pull request #160
Opened 2021-11-21 09:43 UTC by notyourav

- [ ] stb
- [ ] functionvalue
- [ ] fvb

2021-11-25 07:43 UTC, TakaRikka requested changes
mostly just some formatting comments

2021-11-25 07:43 UTC, TakaRikka commented on include/JSystem/JGadget/vector.h
> +    u32 _c;
add offset comment to the left? applies to the rest of the pr too where there's missing offset comments, as well as making them all uppercase to be more consistent with the rest of the project. adding the total size of the struct/class for all the new/changed ones in this pr would also be preferred if its likely all the members are correct

2021-11-25 07:43 UTC, TakaRikka commented on include/JSystem/JStudio/JStudio/fvb-data.h
> +    COMPOSITE_ENUM_SIZE,
I've been preferring to add left hand comments for enum num instead of using = unless necessary

2021-11-25 07:43 UTC, TakaRikka commented on include/JSystem/JStudio/JStudio/stb.h
> +    };
same comment about enum format

2021-11-25 07:43 UTC, TakaRikka commented on libs/JSystem/JStudio/JStudio/fvb.cpp
> +// };
can these be removed?

2021-11-25 07:43 UTC, TakaRikka commented on libs/JSystem/JStudio/JStudio/fvb.cpp
> +// extern "C" static void func_80284240();
remove?

2021-11-25 07:43 UTC, TakaRikka commented on libs/JSystem/JStudio/JStudio/fvb.cpp
> +// COMPILER_STRIP_GATE(0x8039AA00, &data_8039AA00);
remove?

2021-11-25 07:43 UTC, TakaRikka commented on src/d/d_demo.cpp
can all the places with these struct duplicates be replaced with the header include?

2021-11-25 07:43 UTC, TakaRikka commented on libs/JSystem/JStudio/JStudio/stb.cpp
> +#endif
I've been preferring to leave out debug stuff unless necessary to match

2021-11-25 07:43 UTC, TakaRikka commented on libs/JSystem/JStudio/JStudio/stb.cpp
> +#include "msl_c/string.h"
if possible, use the actual MSL_C headers instead of this temp one. this temp one needs to be removed at some point

2021-11-25 09:14 UTC, Julgodis requested changes

2021-11-25 09:14 UTC, Julgodis commented on include/JSystem/JStudio/JStudio/fvb.h
> +    ///* 0x10 */ void* _10;
remove

2021-11-25 09:14 UTC, Julgodis commented on include/JSystem/JStudio/JStudio/functionvalue.h
> +    // u8 FIXME[8];
remove

2021-11-25 09:14 UTC, Julgodis commented on include/JSystem/JStudio/JStudio/functionvalue.h
> +    /* -0x34 */ TFunctionValue::TEOutside mEnd;
Negative offsets?

2021-11-25 09:14 UTC, Julgodis commented on asm/d/kankyo/d_kankyo/setLightTevColorType_MAJI_sub__FP11J3DMaterialP12dKy_tevstr_ci.s
> +/* 801A465C  34 63 4A C8 */	addic. r3, r3, 0x80434AC8@l /* 0x80434AC8@l */
Could you explain why this change is necessary?

2021-11-25 09:19 UTC, notyourav commented on asm/d/kankyo/d_kankyo/setLightTevColorType_MAJI_sub__FP11J3DMaterialP12dKy_tevstr_ci.s
> +/* 801A465C  34 63 4A C8 */	addic. r3, r3, 0x80434AC8@l /* 0x80434AC8@l */
this is the only instruction that causes the unpatched compiler to error.

2021-11-25 09:27 UTC, Julgodis commented on asm/d/kankyo/d_kankyo/setLightTevColorType_MAJI_sub__FP11J3DMaterialP12dKy_tevstr_ci.s
> +/* 801A465C  34 63 4A C8 */	addic. r3, r3, 0x80434AC8@l /* 0x80434AC8@l */
There are actually three places where the unpatched compiler fails, one in main.dol and two in the RELs.
![image](https://user-images.githubusercontent.com/3693193/143414275-85355004-04da-4de8-b2e1-9b232c5cb83f.png)

I believe until we have decompiled the functions with the problematic instructions we should continue to use the patched compiler to maintain possible shiftability.

2021-11-25 17:47 UTC, magcius commented on include/JSystem/JStudio/JStudio/stb.h
> +    };
It's bitflags here, it's required. (Though I might want to see 1 << 0, 1 << 1 format instead)

2021-11-25 18:40 UTC, notyourav commented on include/JSystem/JStudio/JStudio/functionvalue.h
> +    /* -0x34 */ TFunctionValue::TEOutside mEnd;
this was for diagnosing multiple inheritance, but its probably just confusing to be negative

2021-11-25 18:48 UTC, notyourav commented on libs/JSystem/JStudio/JStudio/stb.cpp
> +#endif
I prefer to include them since I tend to focus on the debug rom for its inlines, and it's easier to just copy everything.
Also they are helpful for struct and temp variable names, and also provide better context for what a function is doing. What are other people's thoughts?

2021-11-25 19:12 UTC, Julgodis approved these changes

2021-11-25 23:26 UTC, lepelog commented on include/JSystem/JStudio/JStudio/functionvalue.h
> +        if (temp < *(f64*)&lit_652) {
```suggestion
        if (temp < DOUBLE_LABEL(/* 0.0 */ lit_652)) {
```
I usually put the value of the label there so it's easier to see what it's doing

2021-11-25 23:26 UTC, lepelog commented on libs/JSystem/JStudio/JStudio/functionvalue.cpp
> +    (ExtrapolateParameter)extrapolateParameter_clamp__Q27JStudio13functionvalueFdd,
```suggestion
    (ExtrapolateParameter)JStudio::functionvalue::extrapolateParameter_raw,
    (ExtrapolateParameter)JStudio::functionvalue::extrapolateParameter_repeat,
    (ExtrapolateParameter)JStudio::functionvalue::extrapolateParameter_turn,
    (ExtrapolateParameter)JStudio::functionvalue::extrapolateParameter_clamp,
```
Does something like this work? Maybe that makes it possible to get rid of the casts

2021-11-25 23:26 UTC, lepelog commented on libs/JSystem/JStudio/JStudio/functionvalue.cpp
> +    return interpolateValue_hermite(a1, a2, a3, *(f64*)&lit_652, a4, a5, *(f64*)&lit_652);
```suggestion
    return interpolateValue_hermite(a1, a2, a3, DOUBLE_LABEL(lit_652), a4, a5, DOUBLE_LABEL(lit_652));
```

2021-11-25 23:26 UTC, lepelog commented on libs/JSystem/JStudio/JStudio/functionvalue.cpp
> +        _20 = *(f64*)&lit_652;  // 0.0
double label (also for the rest of the file)

2021-11-25 23:26 UTC, lepelog commented on libs/JSystem/JStudio/JStudio/functionvalue.cpp
> +    if (t < *(f64*)&lit_652)
```suggestion
    if (t < DOUBLE_LABEL(lit_652))
```

2021-11-26 02:58 UTC, TakaRikka commented on libs/JSystem/JStudio/JStudio/stb.cpp
> +#endif
i should rephrase i only mean prefer to leave out debug stuff that was removed in retail, like extra code in functions or unused structs / functions and etc. feel like its unnecessary and confusing for retail imo, and not a super big fan of ifdefs for version control. but all the inlines and variable names and such are definitely good to include.

2021-11-26 10:19 UTC, lepelog approved these changes

2021-11-26 11:28 UTC, TakaRikka approved these changes

2021-11-26 14:50 UTC, merged