daAlink work
zeldaret/tp pull request #165
Opened 2021-12-04 14:00 UTC by TakaRikka

still largely a wip, but a bunch of other files are touched as well so want to get this in before other work overlaps

2021-12-04 23:29 UTC, Julgodis requested changes
Good job 👍 Only had a few comments about style.

What is the `main.dol` progress at now?

I really need to figure the issue with the v-tables:
```c++
asm cXyz::~cXyz() {
// asm cXyz::~cXyz() {
extern "C" asm void __dt__4cXyzFv() {
```

2021-12-04 23:29 UTC, Julgodis commented on include/JSystem/J2DGraph/J2DPane.h
> +    void setUserInfo(u64 info) { mUserInfoTag = info; }
Maybe `setUserInfoTag`? If this isn't the debug version name

2021-12-04 23:29 UTC, Julgodis commented on include/JSystem/J3DGraphBase/J3DMaterial.h
> +    J3DShape* getShape() { return mShape; }
`const` ?

2021-12-04 23:29 UTC, Julgodis commented on include/d/bg/d_bg_s_acch.h
> +    bool ChkWaterHit() { return MaskWaterHit(); }
`const` ?

2021-12-04 23:29 UTC, Julgodis commented on src/d/a/d_a_alink.cpp
> +                                                            60.0f};
add `,` at the end for better formatting

2021-12-04 23:29 UTC, Julgodis commented on src/d/a/d_a_alink.cpp
> +                                                          10.0f};
`,`

2021-12-04 23:29 UTC, Julgodis commented on src/d/a/d_a_alink.cpp
> +                                                    1.2f};
`,`

2021-12-04 23:29 UTC, Julgodis commented on src/d/a/d_a_alink.cpp
> +                                                        3.0f};
`,`

2021-12-04 23:29 UTC, Julgodis commented on src/d/a/d_a_alink.cpp
> +                                                                  5.0f};
`,`

2021-12-04 23:29 UTC, Julgodis commented on src/d/a/d_a_alink.cpp
> +                                                0.0f};
`,`

2021-12-04 23:29 UTC, Julgodis commented on src/d/a/d_a_alink.cpp
> +                                                              0.7f};
`,`

2021-12-04 23:29 UTC, Julgodis commented on src/d/a/d_a_alink.cpp
> +                                                  1.3f};
`,`

2021-12-04 23:41 UTC, TakaRikka commented on include/JSystem/J2DGraph/J2DPane.h
> +    void setUserInfo(u64 info) { mUserInfoTag = info; }
yeah this is from debug

2021-12-04 23:57 UTC, TakaRikka commented on include/JSystem/J3DGraphBase/J3DMaterial.h
> +    J3DShape* getShape() { return mShape; }
this causes some const passing errors in a few functions

2021-12-05 00:24 UTC, magcius commented on include/JSystem/J2DGraph/J2DPane.h
> +    void setUserInfo(u64 info) { mUserInfoTag = info; }
this is likely a void* and is just a random pointer for the user of J2D to throw on whatever they want

2021-12-05 00:29 UTC, TakaRikka commented
main.dol progress is 7.66% .text, 17.37% total

2021-12-05 00:51 UTC, Julgodis approved these changes

2021-12-06 01:15 UTC, merged