JUTXfb: decompile
zeldaret/tp pull request #38
Opened 2020-12-25 06:09 UTC by barzamin

only one mismatch (in the ctor) which is a trivial-looking regalloc issue

2020-12-27 09:30 UTC, notyourav requested changes

2020-12-27 09:30 UTC, notyourav commented on libs/JSystem/JUtility/JUTXfb.cpp
> +        pvVar1 = ::operator new[](size, heap, 0x20);
does this not work here?
```suggestion
        pvVar1 = new[](size, heap, 0x20);
```

2020-12-27 09:30 UTC, notyourav commented on src/m_Do/m_Do_Reset.cpp
> +    return;
this can fit on one line
```suggestion
```

2020-12-27 09:30 UTC, notyourav commented on include/JSystem/JUtility/JUTXfb/JUTXfb.h
> +    void * xfb_buffer[3];
might want to merge and run clang-format (won't pass new CI check otherwise)
```suggestion
    void* xfb_buffer[3];
```

2020-12-28 00:06 UTC, leoetlino commented on libs/JSystem/JUtility/JUTXfb.cpp
> +        pvVar1 = ::operator new[](size, heap, 0x20);
no, syntax error. `new u8[](...)` would work though

2020-12-29 23:01 UTC, Pheenoh approved these changes

2020-12-29 23:01 UTC, merged