JKRAramHeap and JKRAramPiece
zeldaret/tp pull request #53
Opened 2021-01-02 22:17 UTC by Julgodis

* JKRAramHeap OK
* JKRAramPiece OK
* fixed _savegpr_25
* added include/ar/ARQ.h

2021-01-02 23:24 UTC, notyourav requested changes

2021-01-02 23:24 UTC, notyourav commented on include/JSystem/JKernel/JKRAramHeap/JKRAramHeap.h
>      u8 getCurrentGroupID() { return this->mGroupId; }
```suggestion
    u8 getCurrentGroupID() const { return this->mGroupId; }
```
This isn't in the map is it? I would suggest making it const.

2021-01-02 23:24 UTC, notyourav commented on include/JSystem/JKernel/JKRAramHeap/JKRAramHeap.h
>      JKRHeap* getMgrHeap() { return this->mHeap; }
```suggestion
    JKRHeap* getMgrHeap() const { return this->mHeap; }
```
Same here.

2021-01-02 23:24 UTC, notyourav commented on include/JSystem/JKernel/JKRAramPiece/JKRAramPiece.h
> +    /* 0x88 */ OSMessage mMessages[1];
```suggestion
    /* 0x88 */ OSMessage mMessages;
```
Is this necessary?

2021-01-02 23:24 UTC, notyourav commented on include/JSystem/JKernel/JKRAramHeap/JKRAramHeap.h
>      void lock() { OSLockMutex(&this->mMutex); }
```suggestion
    void lock() { OSLockMutex(&mMutex); }
```
Usage of `this` for member access is redundant, goes for the other instances as well.

2021-01-02 23:36 UTC, Julgodis commented on include/JSystem/JKernel/JKRAramPiece/JKRAramPiece.h
> +    /* 0x88 */ OSMessage mMessages[1];
I don't know which way is better:
> OSInitMessageQueue(&mMessageQueue, mMessages, ARRAY_SIZE(mMessages));

or

> OSInitMessageQueue(&mMessageQueue, &mMessage, 1);

2021-01-02 23:39 UTC, notyourav commented on include/JSystem/JKernel/JKRAramPiece/JKRAramPiece.h
> +    /* 0x88 */ OSMessage mMessages[1];
Hmm not sure, curious what @Pheenoh thinks.

2021-01-03 05:19 UTC, Pheenoh commented on include/JSystem/JKernel/JKRAramPiece/JKRAramPiece.h
> +    /* 0x88 */ OSMessage mMessages[1];
```cpp
OSInitMessageQueue(&mMessageQueue, &mMessage, 1);
```

Since 1 is the size of the message queue I don't feel like it's too ambiguous to leave it like that. Could always do a macro if you're looking for verbosity:

```cpp
#define JKRAMCommandMsgSize 1
OSInitMessageQueue(&mMessageQueue, &mMessage, JKRAMCommandMsgSize);
```

2021-01-03 10:29 UTC, Pheenoh approved these changes

2021-01-03 10:29 UTC, merged