JKernel cleanup and DVD types
zeldaret/tp pull request #59
Opened 2021-01-03 21:42 UTC by Julgodis

Updated old JKernel code to follow the code style:
* removed this->
* added const
* added field offsets
* fixed naming
* removed // #include "XXX.s" for matched functions
* DVDFileInfo and DVDCommandBlock

2021-01-03 21:50 UTC, notyourav requested changes

2021-01-03 21:50 UTC, notyourav commented on libs/JSystem/JKernel/JKRDvdFile.cpp
>  #ifndef NONMATCHING
```
#ifndef NONMATCHING
```
This will resolve to choosing the non asm function when NONMATCHING is not defined, is there a reason we need the asm at all now?

2021-01-03 21:50 UTC, notyourav commented on libs/JSystem/JKernel/JKRDvdFile.cpp
> +    // ASSERT((length & 0x1f) == 0);
I think it would be better (if we are keeping track of debug asserts) to use a nulled macro as opposed to comments.

Also, macro should be moved.

2021-01-03 21:57 UTC, Julgodis commented on libs/JSystem/JKernel/JKRDvdFile.cpp
> +    // ASSERT((length & 0x1f) == 0);
Now using nulled macro instead for asserts. 
Moved the nulled macro to global.h for the time being.

2021-01-03 22:17 UTC, notyourav approved these changes

2021-01-04 02:26 UTC, Pheenoh approved these changes

2021-01-04 02:26 UTC, merged