JKRSolidHeap
zeldaret/tp pull request #69
Opened 2021-01-05 18:28 UTC by Julgodis

* decompiled JKRSolidHeap (a few non-matching functions left)
* added const to virtual functions
* JKRHeap::TState

2021-01-05 23:20 UTC, notyourav requested changes

2021-01-05 23:20 UTC, notyourav commented on include/JSystem/JKernel/JKRAssertHeap/JKRAssertHeap.h
> +    /* vt[10] */ virtual void do_free(void*);                  /* override */
```suggestion
    /* vt[10] */ void do_free(void*);                  /* override */
```
Do these need to be marked as virtual?

2021-01-05 23:20 UTC, notyourav commented on libs/JSystem/JKernel/JKRSolidHeap.cpp
> +    if (alignedSize < solidHeapSize) {
```suggestion
    if (alignedSize < solidHeapSize)
```
for consistency, or you should add parentheses around the condition below.

2021-01-06 08:48 UTC, Julgodis commented on include/JSystem/JKernel/JKRAssertHeap/JKRAssertHeap.h
> +    /* vt[10] */ virtual void do_free(void*);                  /* override */
For function that are overridden, virtual is not required. With both the vt[XX] and override comment maybe the virtual keyword is not needed, but this is how I done it for everything else in JKernel. Best would be to use the override keyword, but that was release in C++11, which MWCC ofcourse doesn't support. I am fine with doing it either way as this doesn't really effect the matching of functions. But maybe it's better to change it later, in all classes at once, when we have decided on the style we want.

2021-01-06 10:10 UTC, notyourav approved these changes

2021-01-07 01:33 UTC, merged