Z2AudioLib misc decomp
zeldaret/tp pull request #75
Opened 2021-01-07 01:51 UTC by barzamin

todo explain. just draft rn. merge #64 first

2021-01-08 10:16 UTC, notyourav commented on include/JSystem/JAudio2/JAISound/JAISound.h
> +        // assert on null here in DEBUG (see 8039a7c4 in CHN_debug)
```suggestion
        JUT_ASSERT(sound_ != NULL);
```
Assert macro

2021-01-08 10:16 UTC, notyourav commented on include/JSystem/JAudio2/JAISound/JAISound.h
> +    // private:
Probably private, since I believe they append `_` to privates

2021-01-08 23:55 UTC, barzamin commented on include/JSystem/JAudio2/JAISound/JAISound.h
> +    // private:
it should be, yeah

2021-01-08 23:56 UTC, barzamin commented on include/JSystem/JAudio2/JAISound/JAISound.h
> +        // assert on null here in DEBUG (see 8039a7c4 in CHN_debug)
you mean `mSound` right

2021-01-09 00:02 UTC, notyourav commented on include/JSystem/JAudio2/JAISound/JAISound.h
> +    // private:
Yeah

2021-01-18 04:38 UTC, notyourav requested changes

2021-01-18 04:38 UTC, notyourav commented on include/JSystem/JAudio2/JAISound/JAISound.h
> +    s32 num_prepare_steps;
If this is a canonical name then this might really be a struct (they have a snake case for struct fields convention).

2021-01-18 04:38 UTC, notyourav commented on include/Z2AudioLib/Z2WolfHowlMgr/Z2WolfHowlMgr.h
> +    void getCorrectLine(u8);
Are none of these const in the symbols?

2021-01-18 04:38 UTC, notyourav commented on libs/Z2AudioLib/Z2SeMgr.cpp
> +    this->crowd_size++;
```suggestion
    crowd_size++;
```

2021-01-18 04:38 UTC, notyourav commented on libs/Z2AudioLib/Z2SoundHandles.cpp
> +    for (JSULink<Z2SoundHandlePool>* link = this->getFirst(); link != NULL;
```suggestion
    JSULink<Z2SoundHandlePool>* link;
    for (link = this->getFirst(); link != NULL;
```
is it possible to put the declaration on another line so clang-format doesnt multiline the loop statements?

2021-01-18 04:38 UTC, notyourav commented on libs/Z2AudioLib/Z2SoundObjMgr.cpp
> +    this->setForceBattleArea(false, 700, 0x44c, 0x5dc);
```suggestion
    setForceBattleArea(false, 700, 1100, 1500);
```

2021-01-18 04:44 UTC, barzamin commented on include/JSystem/JAudio2/JAISound/JAISound.h
> +    s32 num_prepare_steps;
it is not it's just whatever was exported from ghidra

2021-01-18 04:45 UTC, barzamin commented on include/Z2AudioLib/Z2WolfHowlMgr/Z2WolfHowlMgr.h
> +    void getCorrectLine(u8);
no, compare:
```
calcPitchMod__13Z2WolfHowlMgrFff
startWolfHowlSound__13Z2WolfHowlMgrFffbf
setCorrectData__13Z2WolfHowlMgrFScP14Z2WolfHowlData
getCorrectLine__13Z2WolfHowlMgrFUc
```

to, say, `hasReset__10Z2AudioMgrCFv`; the mangling is just `F`, not `CF`.

2021-01-19 07:07 UTC, notyourav requested changes

2021-01-19 07:07 UTC, notyourav commented on libs/JSystem/JAudio2/JAUClusterSound.cpp
> +    this->mSound = NULL;
```suggestion
    mSound = NULL;
```

2021-01-19 07:07 UTC, notyourav commented on libs/Z2AudioLib/Z2SceneMgr.cpp
> +    this->mId = soundIdToSet.mId;
```suggestion
    mId = soundIdToSet.mId;
```

2021-01-19 07:07 UTC, notyourav commented on libs/Z2AudioLib/Z2SeMgr.cpp
> +    this->field_0x18 = -1;
```suggestion
    field_0x18 = -1;
```

2021-01-19 07:07 UTC, notyourav commented on libs/Z2AudioLib/Z2SeMgr.cpp
> +    this->field_0x8 = zero;
```suggestion
    field_0x8 = zero;
```

2021-01-19 07:07 UTC, notyourav commented on libs/Z2AudioLib/Z2SoundHandles.cpp
> +    this->deleteHandlesPool();
```suggestion
    deleteHandlesPool();
```

2021-01-19 07:07 UTC, notyourav commented on libs/Z2AudioLib/Z2SoundHandles.cpp
> +    for (JSULink<Z2SoundHandlePool>* link = this->getFirst(); link != NULL;
```suggestion
    JSULink<Z2SoundHandlePool>* link;
    for (link = getFirst(); link != NULL;
```

2021-01-19 07:07 UTC, notyourav commented on libs/Z2AudioLib/Z2SoundHandles.cpp
> +    for (JSULink<Z2SoundHandlePool>* link = this->getFirst(); link != NULL;
```suggestion
    JSULink<Z2SoundHandlePool>* link;
    for (link = getFirst(); link != NULL;
```

2021-01-19 07:07 UTC, notyourav commented on libs/Z2AudioLib/Z2SoundObjMgr.cpp
> +    this->field_0x19 = 0;
```suggestion
    field_0x19 = 0;
```

2021-01-19 07:07 UTC, notyourav commented on libs/Z2AudioLib/Z2SoundObjMgr.cpp
> +        if (this->field_0x1a >= this->field_0x16) {
```suggestion
        if (field_0x1a >= field_0x16) {
```

2021-01-19 07:07 UTC, notyourav commented on libs/Z2AudioLib/Z2SoundObjMgr.cpp
> +    while (link = this->getFirst(), link != NULL) {
```suggestion
    while (link = getFirst(), link != NULL) {
```

2021-01-19 07:07 UTC, notyourav commented on libs/Z2AudioLib/Z2SoundObject.cpp
> +    this->deleteObject();
```suggestion
    deleteObject();
```

2021-01-19 07:07 UTC, notyourav commented on libs/Z2AudioLib/Z2SoundObject.cpp
> +    this->initHandlesPool(pNumHandles);
```suggestion
    initHandlesPool(pNumHandles);
```

2021-01-19 23:09 UTC, barzamin commented on libs/Z2AudioLib/Z2SoundObjMgr.cpp
> +    while (link = this->getFirst(), link != NULL) {
leaving `this->` because it's an inherited member fn

2021-01-21 23:44 UTC, barzamin commented
@notyourav are you okay w/ merging and make decisions about conventions post-hoc since there's no global consistency rn anyway?

2021-01-21 23:53 UTC, notyourav approved these changes

2021-01-22 04:16 UTC, merged