JKernel: static class variables and more matches
zeldaret/tp pull request #78
Opened 2021-01-08 22:18 UTC by Julgodis

* abs, memset
* changed JKRCompression to typedef (this will make signatures make)
* changed some static variables in JKernel from lbl_XXXXXXXX to their real name
* JKRArchive setExpandSize and getExpandSize matched
* JKRDvdFile 100% complete
* JKRDvdArchive matched a few, still problems with instruction ordering

2021-01-08 23:29 UTC, notyourav requested changes

2021-01-08 23:29 UTC, notyourav commented on include/JSystem/JKernel/SArc.h
> +} __attribute__((aligned(32)));
Is `__attribute__` valid in mwcc? Curious if removing this changes anything, or if its simply being ignored by the preprocessor.

2021-01-08 23:29 UTC, notyourav commented on libs/JSystem/JKernel/JKRHeap.cpp
> +    mCodeStart = OS_GLOBAL_ADDR(void, 0x80000000);
```suggestion
    mCodeStart = OSPhysicalToCached(void);
```
inline

2021-01-08 23:29 UTC, notyourav commented on libs/JSystem/JKernel/JKRHeap.cpp
> +    mMemorySize = OS_GLOBAL(u32, 0x80000028);
I think this might be a struct offset from the address retrieved above (`0x80000000`)
Ghidra outputs (debug):
```cpp
_mMemorySize = *(undefined4 *)(_mCodeStart + 0x28);
```
Also the inline for retrieving the right address is only called once.

2021-01-08 23:29 UTC, notyourav commented on include/global.h
> +#define FLAG_HAS(V, F) (((V) & (F)) == 0)
```suggestion
#define FLAG_ON(V, F) (((V) & (F)) == 0)
```
might be more verbose

2021-01-09 01:09 UTC, Julgodis commented on include/JSystem/JKernel/SArc.h
> +} __attribute__((aligned(32)));
Don't known if it's valid or not, tried it in the function JKRDvdArchive::fetchResource_subroutine. Forgot to remove it before committing, good catch!

2021-01-09 09:06 UTC, notyourav approved these changes

2021-01-10 20:15 UTC, Julgodis commented
These changed are already merged. As pull request #80 was based on this pull request, and #80 is already merged.

2021-01-10 20:15 UTC, closed without merging