dBgS: Decomp dBgS_PolyPassChk
zeldaret/tp pull request #92
Opened 2021-01-22 13:07 UTC by lioncash

A fairly straightforward class with nothing too hard to figure out, given it's just a class encapsulating a set of bools.

2021-01-22 22:35 UTC, notyourav requested changes

2021-01-22 22:35 UTC, notyourav commented on src/d/d_bg/d_bg_s_poly_pass_chk.cpp
> +// __ct__16dBgS_PolyPassChkFv
No need for these comments if the symbol has been fully resolved

2021-01-22 22:35 UTC, notyourav commented on src/d/d_bg/d_bg_s_poly_pass_chk.cpp
> +    mObject = chk.mObject;
this is an inlined operator=

2021-01-22 22:35 UTC, notyourav commented on src/d/d_bg/d_bg_s_poly_pass_chk.cpp
> +    if (mObject || mCamera || mLink || mArrow || mBomb || mBoomerang || mRope || mUnderwaterRoof) {
Lots of inlines missing, might want to check debug
```cpp
bool __thiscall ChkNoHorse(dBgS_PolyPassChk *this) {
    int temp;
    bool result;
    
    temp = ChkObj(this);
    if (((((temp == 0) && (temp = ChkCam(this), temp == 0)) && (temp = ChkLink(this), temp == 0)) && ((temp = ChkArrow(this), temp == 0 && (temp = ChkBomb(this), temp == 0)))) &&
       ((temp = ChkBoomerang(this), temp == 0 && ((temp = ChkRope(this), temp == 0 && (temp = ChkUnderwaterRoof(this), temp == 0)))))) {
        temp = ChkHorse(this);
        if (temp == 0) {
            result = true;
        }
        else {
            result = false;
        }
    }
    else {
        result = true;
    }
    return result;
}
```

2021-01-22 22:35 UTC, notyourav commented on src/d/d_bg/d_bg_s_poly_pass_chk.cpp
> +asm void func_80078FAC(void) {
Keep it just a declaration in the header. This dtor is never directly referenced apparently so it needs to be force linked. According to the link script, only `func_80078FAC` is being force linked, and not `__dt__16cBgS_PolyPassChkFv`. This means that the definition in the header is being thrown away at link time, while this one stays. 

I would suggest giving this the proper symbol and then replacing `func_80078FAC`  with `__dt__16cBgS_PolyPassChkFv` in the FORCEACTIVE section.

2021-01-23 02:54 UTC, lioncash commented on src/d/d_bg/d_bg_s_poly_pass_chk.cpp
> +asm void func_80078FAC(void) {
I've tried doing what you suggested, but this results in the final executable not matching anymore. e.g. `__dt__16cBgS_PolyPassChkFv` exists as a function prototype declaration already in the header, so I replaced `func_80078FAC` with it in the link script, but it doesn't seem to work. Can you provide an example of what you mean?

2021-01-23 04:07 UTC, notyourav commented on src/d/d_bg/d_bg_s_poly_pass_chk.cpp
> +asm void func_80078FAC(void) {
```diff
class cBgS_PolyPassChk {
public:
-    virtual ~cBgS_PolyPassChk() {}
+    virtual ~cBgS_PolyPassChk();
};
```
```diff
+asm void func_80078FAC(void) {
-cBgS_PolyPassChk::~cBgS_PolyPassChk() {}
```
although this will likely not be matching since `cBgS_PolyPassChk` doesn't appear to be implemented yet.

2021-01-23 04:41 UTC, lioncash commented on src/d/d_bg/d_bg_s_poly_pass_chk.cpp
> +asm void func_80078FAC(void) {
Ah, yeah, was definitely mixing up `cBgS_PolyPassChk ` and `dBgS_PolyPassChk`, thanks! Applied the change.

2021-01-23 06:27 UTC, notyourav approved these changes

2021-01-25 05:32 UTC, merged